/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class BulletSpawnedListener : MonoBehaviour
    {
        public UnityEvent<BulletSpawned> onBulletSpawned = new();
        public void OnEnable()
        {
            Channel.BulletSpawned.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.BulletSpawned.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.BulletSpawned>.Args args)
        {
            onBulletSpawned.Invoke(args.Data);
        }
    }
}