/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class BulletSpawnedTrigger : MonoBehaviour
    {
        public void Fire(UnityEngine.Vector3 direction)
        {
            Channel.BulletSpawned.Dispatch(new MyProject.Events.BulletSpawned(direction));
        }

        public void FireAt(UnityEngine.Vector3 direction, UnityEngine.Vector3 __position)
        {
            Channel.BulletSpawned.Dispatch(new MyProject.Events.BulletSpawned(direction), __position);
        }
    }
}