/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class BulletMissedTrigger : MonoBehaviour
    {
        public void Fire()
        {
            Channel.BulletMissed.Dispatch(new MyProject.Events.BulletMissed());
        }

        public void FireAt(UnityEngine.Vector3 position)
        {
            Channel.BulletMissed.Dispatch(new MyProject.Events.BulletMissed(), position);
        }
    }
}