/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class BulletHitTrigger : MonoBehaviour
    {
        public void Fire(UnityEngine.Vector3 position)
        {
            Channel.BulletHit.Dispatch(new MyProject.Events.BulletHit(position));
        }

        public void FireAt(UnityEngine.Vector3 position, UnityEngine.Vector3 __position)
        {
            Channel.BulletHit.Dispatch(new MyProject.Events.BulletHit(position), __position);
        }
    }
}