/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class ChatMessageReceivedListener : MonoBehaviour
    {
        public UnityEvent<ChatMessageReceived> onChatMessageReceived = new();
        public void OnEnable()
        {
            Channel.ChatMessageReceived.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.ChatMessageReceived.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.ChatMessageReceived>.Args args)
        {
            onChatMessageReceived.Invoke(args.Data);
        }
    }
}