/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class ChatMessageReceivedTrigger : MonoBehaviour
    {
        public void Fire(System.String name, System.String message, MyProject.Events.ChatMessageKind kind)
        {
            Channel.ChatMessageReceived.Dispatch(new MyProject.Events.ChatMessageReceived(name, message, kind));
        }

        public void FireAt(System.String name, System.String message, MyProject.Events.ChatMessageKind kind, UnityEngine.Vector3 __position)
        {
            Channel.ChatMessageReceived.Dispatch(new MyProject.Events.ChatMessageReceived(name, message, kind), __position);
        }
    }
}