/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class GameStartedListener : MonoBehaviour
    {
        public UnityEvent<GameStarted> onGameStarted = new();
        public void OnEnable()
        {
            Channel.GameStarted.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.GameStarted.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.GameStarted>.Args args)
        {
            onGameStarted.Invoke(args.Data);
        }
    }
}