/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class GameScoreTrigger : MonoBehaviour
    {
        public void Fire(System.Int32 score)
        {
            Channel.GameScore.Dispatch(new MyProject.Events.GameScore(score));
        }

        public void FireAt(System.Int32 score, UnityEngine.Vector3 __position)
        {
            Channel.GameScore.Dispatch(new MyProject.Events.GameScore(score), __position);
        }
    }
}