/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class GameStartedTrigger : MonoBehaviour
    {
        public void Fire()
        {
            Channel.GameStarted.Dispatch(new MyProject.Events.GameStarted());
        }

        public void FireAt(UnityEngine.Vector3 position)
        {
            Channel.GameStarted.Dispatch(new MyProject.Events.GameStarted(), position);
        }
    }
}