/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerSpawnedTrigger : MonoBehaviour
    {
        public void Fire(UnityEngine.GameObject player)
        {
            Channel.PlayerSpawned.Dispatch(new MyProject.Events.PlayerSpawned(player));
        }

        public void FireAt(UnityEngine.GameObject player, UnityEngine.Vector3 __position)
        {
            Channel.PlayerSpawned.Dispatch(new MyProject.Events.PlayerSpawned(player), __position);
        }
    }
}