/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerDiedTrigger : MonoBehaviour
    {
        public void Fire()
        {
            Channel.PlayerDied.Dispatch(new MyProject.Events.PlayerDied());
        }

        public void FireAt(UnityEngine.Vector3 position)
        {
            Channel.PlayerDied.Dispatch(new MyProject.Events.PlayerDied(), position);
        }
    }
}