/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerMoveInputTrigger : MonoBehaviour
    {
        public void Fire(UnityEngine.Vector3 direction)
        {
            Channel.PlayerMoveInput.Dispatch(new MyProject.Events.PlayerMoveInput(direction));
        }

        public void FireAt(UnityEngine.Vector3 direction, UnityEngine.Vector3 __position)
        {
            Channel.PlayerMoveInput.Dispatch(new MyProject.Events.PlayerMoveInput(direction), __position);
        }
    }
}