/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerMoveInputListener : MonoBehaviour
    {
        public UnityEvent<PlayerMoveInput> onPlayerMoveInput = new();
        public void OnEnable()
        {
            Channel.PlayerMoveInput.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.PlayerMoveInput.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.PlayerMoveInput>.Args args)
        {
            onPlayerMoveInput.Invoke(args.Data);
        }
    }
}