/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerHealthListener : MonoBehaviour
    {
        public UnityEvent<PlayerHealth> onPlayerHealth = new();
        public void OnEnable()
        {
            Channel.PlayerHealth.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.PlayerHealth.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.PlayerHealth>.Args args)
        {
            onPlayerHealth.Invoke(args.Data);
        }
    }
}