/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerDiedListener : MonoBehaviour
    {
        public UnityEvent<PlayerDied> onPlayerDied = new();
        public void OnEnable()
        {
            Channel.PlayerDied.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.PlayerDied.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.PlayerDied>.Args args)
        {
            onPlayerDied.Invoke(args.Data);
        }
    }
}