/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerSpawnedListener : MonoBehaviour
    {
        public UnityEvent<PlayerSpawned> onPlayerSpawned = new();
        public void OnEnable()
        {
            Channel.PlayerSpawned.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.PlayerSpawned.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.PlayerSpawned>.Args args)
        {
            onPlayerSpawned.Invoke(args.Data);
        }
    }
}