/// <auto-generated/>
using System;
using UnityEngine;
using UnityEngine.Events;

namespace MyProject.Events
{
    public class PlayerHitListener : MonoBehaviour
    {
        public UnityEvent<PlayerHit> onPlayerHit = new();
        public void OnEnable()
        {
            Channel.PlayerHit.Fired += OnTrigger;
        }

        public void OnDisable()
        {
            Channel.PlayerHit.Fired -= OnTrigger;
        }

        private void OnTrigger(Event<MyProject.Events.PlayerHit>.Args args)
        {
            onPlayerHit.Invoke(args.Data);
        }
    }
}