name: Changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Clone settings
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Reset files
        run: |
          git clean -ffdx && git reset --hard HEAD

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install PNPM
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - id: versions
        name: Check versions
        run: |
          export HUSKY=0

          PACKAGE_VERSION=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json').toString()).version)")
          echo "current_version=${PACKAGE_VERSION}" > $GITHUB_OUTPUT

          pnpm changeset version

          PACKAGE_VERSION=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json').toString()).version)")
          echo "next_version=${PACKAGE_VERSION}" > $GITHUB_OUTPUT

      - name: Pull Request
        uses: peter-evans/create-pull-request@v6
        if: steps.versions.outputs.current_version != steps.versions.outputs.next_version
        with:
          title: Apply changesets (v${{ steps.versions.outputs.next_version }})
          author: João <joao@linefusion.io>
          committer: Black Rabbit <br@linefusion.io>
          commit-message: "chore(ver): applies all changesets"
          body: |
            This applies all pending changesets for the next release.
          branch: release
          delete-branch: true
          assignees: wolfulus
          labels: release

